[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "~2.0"
futures = "0.1"
#grpcio = "0.3"
raft = "0.3"

[dependencies.grpcio]
git = "https://github.com/overvenus/grpc-rs.git"
features = [ "secure" ]
branch = "v0.4.0"
